# -*- coding: utf-8 -*-
{
    "name": "Dankbit",
    "version": "18.0.0.0.2",
    "category": "Options Greeks",
    "author": "Farid Shahy <fshahy@gmail.com>",
    "license": "Other OSI approved licence",
    "summary": "",
    "description": "",
    "depends": ["website"],
    "data": [
        "data/ir_rule.xml",
        "data/ir_cron.xml",
        "data/ir_action.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/trade_views.xml",
        "views/zones_extrema_views.xml",
        "views/liquidity_snapshot_views.xml",
        "views/http_log_views.xml",
        "views/dankbit_templates.xml",
        "wizard/plot_wizard_view.xml",
        "wizard/zones_wizard_view.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}