# -*- coding: utf-8 -*-
{
    "name": "Dankbit",
    "version": "18.0.0.0.27",
    "category": "Options Greeks",
    "author": "Farid Shahy <fshahy@gmail.com>",
    "license": "Other OSI approved licence",
    "summary": "",
    "description": "",
    "depends": ["website"],
    "data": [
        "data/ir_rule.xml",
        "data/ir_cron.xml",
        "data/ir_action.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_views.xml",
        "views/trade_views.xml",
        "views/bands_views.xml",
        "views/live_band_views.xml",
        "views/forecast_snapshot_views.xml",
        "views/forecast_log_views.xml",
        "views/forecast_next_candle_views.xml",
        "views/signal_bot_views.xml",
        "views/http_log_views.xml",
        "views/dankbit_templates.xml",
        "views/gamma_triple_chart_templates.xml",
        "views/four_leg_gamma_chart_templates.xml",
        "views/mwa_gamma_chart_templates.xml",
        "views/aaaa_gamma_chart_templates.xml",
        "wizard/plot_wizard_view.xml",
        "wizard/zones_wizard_view.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
